version: '2'
services:
  web:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      POSTGRES_ADDRESS: db
      POSTGRES_DATABASE: stoctor_dev
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    entrypoint: mix phoenix.server
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
